name: Daily Repository Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # JST 7:00

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  TZ: 'Asia/Tokyo'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'main'
        fetch-depth: 0 # this is important to fetch all history

    - name: Pull latest from original
      run: |
        git remote add upstream https://github.com/pluralitybook/plurality.git
        git pull --rebase upstream main
        git push origin main

    - name: Run translation
      run: |
        python autotrans/main.py

    - name: Commit translation
      run: |
        autotrans/commit.sh
